baseURL = "http://vuotto.tech/"
languageCode = "en-us"
title = "Simone Vuotto 2020"
theme = "personal-web"
copyright="© Simone Vuotto"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Simone Vuotto"
  sub = "Software Engineer, Phd Student"

[params.sidebar]
  backgroundImage = '/images/banner.jpg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = 'rgba(0,0,0,1),rgba(0,0,0,0.1)' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/vuotto.jpg" # - default "/images/edna-west.jpg"

[params.social]
  github = "https://github.com/SimoV8"
  twitter = "https://twitter.com/simo_v8"
  linkedin = "https://www.linkedin.com/in/svuotto/"


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
